import hashlib

from core.security.watermarker import ChainMarkWatermarker


def test_watermark_preserves_readability():
    original = "This is ordinary readable legal compliance text."
    result = ChainMarkWatermarker(tenant_id="tenant-a").watermark(original, visible=False)
    assert result.text.replace("\u200b", "").replace("\u200c", "") == original


def test_detect_finds_watermark():
    wm = ChainMarkWatermarker(tenant_id="tenant-a")
    result = wm.watermark("A sufficiently long legal response with several words.", visible=False)
    detection = wm.detect(result.text)
    assert detection.is_watermarked
    assert detection.watermark_valid
    assert detection.timestamp == result.metadata["timestamp"]


def test_detect_non_watermarked_text():
    assert not ChainMarkWatermarker().detect("No watermark is present here.").is_watermarked


def test_watermark_survives_copy_paste():
    wm = ChainMarkWatermarker()
    result = wm.watermark("Copy and paste should preserve invisible Unicode characters.", visible=False)
    copied = ("prefix " + result.text + " suffix")[:]
    assert wm.detect(copied).watermark_valid


def test_metadata_signature_verification():
    wm = ChainMarkWatermarker(secret_key=b"a" * 32)
    result = wm.watermark("Signed provenance metadata is returned separately.", visible=False)
    assert wm.verify_metadata(result.metadata, result.text)
    altered = result.text + " altered"
    assert not wm.verify_metadata(result.metadata, altered)


def test_visible_marker_fr_and_en():
    wm = ChainMarkWatermarker()
    fr = wm.watermark("Réponse juridique.", language="fr", visible=True)
    en = wm.watermark("Legal response.", language="en", visible=True)
    assert fr.visible_marker_added
    fr_clean = fr.text.replace("\u200b", "").replace("\u200c", "")
    en_clean = en.text.replace("\u200b", "").replace("\u200c", "")
    assert "Ce contenu a été généré par IA" in fr_clean
    assert "This content was generated by AI" in en_clean


def test_no_spaces_edge_case():
    wm = ChainMarkWatermarker()
    result = wm.watermark("TexteSansEspaces", visible=False)
    assert result.text.replace("\u200b", "").replace("\u200c", "") == "TexteSansEspaces"
    assert wm.detect(result.text).watermark_valid


def test_short_text():
    wm = ChainMarkWatermarker()
    result = wm.watermark("Court.", visible=False)
    assert wm.detect(result.text).watermark_valid


def test_crc_validation_catches_corruption():
    wm = ChainMarkWatermarker()
    result = wm.watermark("A response with enough words for a machine-readable watermark.", visible=False)
    zero_width_positions = [i for i, c in enumerate(result.text) if c in ("\u200b", "\u200c")]
    assert zero_width_positions
    # Corrupt a bit AFTER the magic prefix (position >= 16 bits) so the magic
    # is still found but the CRC check fails.
    # Each zero-width char = 1 bit. Magic = 16 bits. Corrupt at least 1 bit after offset 16.
    index = zero_width_positions[min(20, len(zero_width_positions) - 1)]
    corrupted_char = "\u200c" if result.text[index] == "\u200b" else "\u200b"
    corrupted = result.text[:index] + corrupted_char + result.text[index + 1:]
    detection = wm.detect(corrupted)
    assert detection.is_watermarked
    assert not detection.watermark_valid
