from __future__ import annotations

import base64
import hashlib
import hmac
import json
import logging
import secrets
import time
import uuid
from dataclasses import dataclass
from typing import Optional

try:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey, Ed25519PublicKey
    _HAS_ED25519 = True
except ImportError:  # pragma: no cover
    _HAS_ED25519 = False


logger = logging.getLogger("cortex_leman.journal.security.watermarker")

_ZERO_WIDTH = "\u200b"
_ZERO_WIDTH_ONE = "\u200c"
_MAGIC = b"\xc0\xde"
_PAYLOAD_BITS = 72  # 16-bit magic + 16-bit tenant + 32-bit timestamp + 8-bit CRC
_VERSION = "5"
_MARKERS = {
    "fr": "[Ce contenu a été généré par IA — Cortex Leman]",
    "en": "[This content was generated by AI — Cortex Leman]",
    "de": "[Dieser Inhalt wurde von einer KI erzeugt — Cortex Leman]",
    "it": "[Questo contenuto è stato generato dall'IA — Cortex Leman]",
}


@dataclass(frozen=True)
class WatermarkResult:
    text: str
    metadata: dict
    visible_marker_added: bool


@dataclass(frozen=True)
class DetectionResult:
    is_watermarked: bool
    tenant_id: Optional[str] = None
    timestamp: Optional[int] = None
    watermark_valid: bool = False
    content_hash_match: Optional[bool] = None


def _crc8(data: bytes) -> int:
    crc = 0
    for value in data:
        crc ^= value
        for _ in range(8):
            crc = ((crc << 1) ^ 0x07) & 0xFF if crc & 0x80 else (crc << 1) & 0xFF
    return crc


def _canonical_json(value: dict) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def _bits_to_bytes(bits: str) -> bytes:
    return bytes(int(bits[i:i + 8], 2) for i in range(0, len(bits), 8))


class ChainMarkWatermarker:
    """Model-independent text watermarking and provenance signing.

    The Unicode marker is deliberately small and machine-readable. It is not
    intended to provide confidentiality; the cryptographic metadata does that
    for provenance and integrity.
    """

    def __init__(self, secret_key: bytes = None, tenant_id: str = "default"):
        if not isinstance(tenant_id, str) or not tenant_id:
            raise ValueError("tenant_id must be a non-empty string")
        self.tenant_id = tenant_id
        self._tenant_number = int.from_bytes(hashlib.sha256(tenant_id.encode("utf-8")).digest()[:2], "big")
        self._hmac_key = secret_key
        self._private_key = None
        self._public_key = None
        if secret_key is None:
            if _HAS_ED25519:
                self._private_key = Ed25519PrivateKey.generate()
                self._public_key = self._private_key.public_key()
            else:
                self._hmac_key = secrets.token_bytes(32)
        elif not isinstance(secret_key, bytes) or len(secret_key) < 16:
            raise ValueError("secret_key must contain at least 16 bytes")

    def _payload(self, timestamp: int) -> bytes:
        body = _MAGIC + self._tenant_number.to_bytes(2, "big") + timestamp.to_bytes(4, "big")
        return body + bytes([_crc8(body)])

    @staticmethod
    def _encode_bits(payload: bytes) -> str:
        return "".join(f"{byte:08b}" for byte in payload)

    @staticmethod
    def _inject(text: str, bits: str) -> str:
        if not bits:
            return text
        # Full payload as contiguous block at the very start — guarantees that
        # any substring taken from the beginning of the text retains the
        # complete 72-bit watermark (magic + tenant + timestamp + CRC).
        header = "".join(_ZERO_WIDTH_ONE if b == "1" else _ZERO_WIDTH for b in bits)

        # Redundant copies spread across word boundaries for mid-text fragments
        boundaries = [i + 1 for i, char in enumerate(text) if char.isspace()]
        if boundaries:
            step = max(1, len(boundaries) // len(bits))
            selected = boundaries[::step][:len(bits)]
        else:
            selected = []
        pieces = []
        last = 0
        used = 0
        for position in selected:
            pieces.append(text[last:position])
            pieces.append(_ZERO_WIDTH_ONE if bits[used] == "1" else _ZERO_WIDTH)
            last = position
            used += 1
        body = "".join(pieces) + text[last:]
        if used < len(bits):
            body += "".join(_ZERO_WIDTH_ONE if b == "1" else _ZERO_WIDTH for b in bits[used:])
        return header + body

    def _sign(self, payload: bytes) -> tuple[str, str]:
        if self._private_key is not None:
            signature = self._private_key.sign(payload)
            return "Ed25519", base64.b64encode(signature).decode("ascii")
        signature = hmac.new(self._hmac_key, payload, hashlib.sha256).digest()
        return "HMAC-SHA256", base64.b64encode(signature).decode("ascii")

    def watermark(self, text: str, model: str = "", visible: bool = True, language: str = "fr") -> WatermarkResult:
        if not isinstance(text, str):
            raise TypeError("text must be a string")
        language = language.lower().split("-")[0]
        marker_added = bool(visible)
        base = text
        if marker_added:
            marker = _MARKERS.get(language, _MARKERS["en"])
            base = base.rstrip() + "\n\n" + marker
        timestamp = int(time.time())
        marked_text = self._inject(base, self._encode_bits(self._payload(timestamp)))
        metadata = {
            "watermark_id": str(uuid.uuid4()),
            "tenant_id": self.tenant_id,
            "model": model,
            "timestamp": timestamp,
            "content_hash": hashlib.sha256(marked_text.encode("utf-8")).hexdigest(),
            "cortex_leman_version": _VERSION,
        }
        algorithm, signature = self._sign(_canonical_json(metadata))
        metadata["signature_algorithm"] = algorithm
        metadata["signature"] = signature
        if algorithm == "Ed25519":
            metadata["public_key"] = base64.b64encode(
                self._public_key.public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
            ).decode("ascii")
        logger.info("text watermark created", extra={"watermark_id": metadata["watermark_id"], "tenant_id": self.tenant_id})
        return WatermarkResult(marked_text, metadata, marker_added)

    def detect(self, text: str) -> DetectionResult:
        if not isinstance(text, str):
            raise TypeError("text must be a string")
        bits = "".join("1" if char == _ZERO_WIDTH_ONE else "0" for char in text if char in (_ZERO_WIDTH, _ZERO_WIDTH_ONE))
        for offset in range(max(0, len(bits) - _PAYLOAD_BITS + 1)):
            candidate = _bits_to_bytes(bits[offset:offset + _PAYLOAD_BITS])
            if len(candidate) != 9 or candidate[:2] != _MAGIC:
                continue
            body, checksum = candidate[:-1], candidate[-1]
            valid = _crc8(body) == checksum
            tenant_number = int.from_bytes(body[2:4], "big")
            timestamp = int.from_bytes(body[4:8], "big")
            if valid:
                logger.info("valid text watermark detected", extra={"tenant_number": tenant_number, "timestamp": timestamp})
                return DetectionResult(True, str(tenant_number), timestamp, True, None)
            return DetectionResult(True, str(tenant_number), timestamp, False, None)
        return DetectionResult(False, None, None, False, None)

    def verify_metadata(self, metadata: dict, text: str) -> bool:
        if not isinstance(metadata, dict) or not isinstance(text, str):
            return False
        try:
            expected_hash = metadata["content_hash"]
            if not hmac.compare_digest(expected_hash, hashlib.sha256(text.encode("utf-8")).hexdigest()):
                return False
            signature = base64.b64decode(metadata["signature"], validate=True)
            unsigned = {key: value for key, value in metadata.items() if key not in ("signature", "signature_algorithm", "public_key")}
            payload = _canonical_json(unsigned)
            algorithm = metadata["signature_algorithm"]
            if algorithm == "Ed25519":
                if not _HAS_ED25519:
                    return False
                public_bytes = base64.b64decode(metadata["public_key"], validate=True)
                Ed25519PublicKey.from_public_bytes(public_bytes).verify(signature, payload)
                return True
            if algorithm == "HMAC-SHA256" and self._hmac_key is not None:
                expected = hmac.new(self._hmac_key, payload, hashlib.sha256).digest()
                return hmac.compare_digest(signature, expected)
        except (KeyError, ValueError, TypeError, Exception) as exc:
            logger.warning("metadata verification failed: %s", exc)
        return False
